name: upgrade EKS

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

 # Triggers the workflow when an issue in the workflow's repository is created or modified.
  issues:
    types: [opened, edited]

  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:


jobs:

  # job 1, jobs run in parallel
  Back-up:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Configure AWS credentials to access EKS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::XXXXXX:role/GitHubActionsEKSRole
          aws-region: us-west-2

      - name: Backup Kubernetes Resources
        run: |
          BACKUP_NAME="backup-$(date +"%Y-%m-%d-%H-%M-%S")"
          BACKUP_DIR="/k8s-backup/BACKUP_NAME"
          mkdir -p BACKUP_DIR

          kubectl get all -A -o yaml > "$BACKUP_DIR/backup.yaml",
          kubectl get secrets -A -o yaml > "$BACKUP_DIR/secrets.yaml",
          kubectl get certificates -A -o yaml > "$BACKUP_DIR/certs.yaml",
          kubectl get configmap -A -o yaml > "$BACKUP_DIR/configmap.yaml",
          kubectl get svc -n istio-system -o yaml > "$BACKUP_DIR/istio-svc.yaml",
          kubectl get secrets -n istio-system -o yaml > "$BACKUP_DIR/istio-secrets.yaml".

      - name: Backup with Velero
        run: |
          #velero create backup "$BACKUP_NAME" --include-namespaces cisco,vault,cert-manager,istio-system

  # job 2
  upgrade-EKS:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Configure AWS credentials to access EKS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::XXXXXX:role/GitHubActionsEKSRole
          aws-region: us-west-2

      # run helm-diff script to see what needs to be updated
      - name: Run helm-diff
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::XXXXXX:role/GitHubActionsEKSRole
          aws-region: us-west-2
